spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

openlineage:
  enabled: true
  namespace: demo-batch
  transport: http
  http:
    url: http://localhost:8000
  granularity:
    job-events: true
    step-events: true
    chunk-events: true
    chunk-event-interval: 1

logging:
  level:
    io.openlineage.batch: DEBUG
